function [Con,mu] = de_connector4DMap(sI,sH,hpl,nFreq,nOrientnumCon,distn,rds,sig,dbg,tol,weight_factor, want_fully_connected)

        nHidPerLayer = model.nHidden/nInputLayers;
        Con = spalloc( 2*prod(model.nInput) + model.nHidden, 2*prod(model.nInput) + model.nHidden, 2*model.nHidden*model.nConns + 2*prod(model.nInput)+model.nHidden );

        for i=1:nInputLayers

            [C, mu] = de_connector2D(model.nInput(1:2), ...
										  model.nHidden/nInputLayers, ...
										  model.hpl,...
										  model.nConns,...
										  model.distn{1}, ...
										  model.mu,...
										  model.sigma,...
										  model.ac.debug, ...
										  model.ac.tol);

            Con( prod(model.nInput) + (i-1)*nHidPerLayer + [1:nHidPerLayer], (i-1)*nPix+[1:nPix]) = C(nPix+[1:nHidPerLayer],[1:nPix]); %Input->Hidden
            Con( prod(model.nInput) +model.nHidden + (i-1)*nPix + [1:nPix], prod(model.nInput) + (i-1)*nHidPerLayer + [1:nHidPerLayer]) = C(nPix+nHidPerLayer+[1:nPix], nPix+[1:nHidPerLayer]); %Hidden->Output
		end;
